/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "calculare-test.check" instead.
 */

#include <check.h>

#line 1 "calculare-test.check"
#include "calculare.h"
#include <string.h>

char buffer[256];

START_TEST(int2roman_test)
{
#line 7
	ck_assert_str_eq ((int2roman (3, buffer), buffer), "III");
	ck_assert_str_eq ((int2roman (1, buffer), buffer), "I");
	ck_assert_str_eq ((int2roman (2, buffer), buffer), "II");
	ck_assert_str_eq ((int2roman (4, buffer), buffer), "IV");
	ck_assert_str_eq ((int2roman (400, buffer), buffer), "CD");
	ck_assert_str_eq ((int2roman (40, buffer), buffer), "XL");
	ck_assert_str_eq ((int2roman (5, buffer), buffer), "V");


}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, int2roman_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
